spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
springdoc:
  pathsToMatch:
    - /api/**/v1/**
#    - /auth/**
  swagger-ui:
    use-root-path: true